
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package toy3;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int CHAR_CONST = 49;
  public static final int ASSIGNDECL = 31;
  public static final int CHAR = 17;
  public static final int GE = 33;
  public static final int DOUBLE_CONST = 47;
  public static final int DOUBLE = 15;
  public static final int SEMI = 5;
  public static final int INT = 13;
  public static final int OUT = 42;
  public static final int RBRAC = 12;
  public static final int REF = 44;
  public static final int MINUS = 27;
  public static final int OUTNL = 43;
  public static final int AND = 39;
  public static final int NOT = 38;
  public static final int LT = 34;
  public static final int RPAR = 10;
  public static final int IN = 41;
  public static final int OR = 40;
  public static final int BOOL = 14;
  public static final int COMMA = 7;
  public static final int DIV = 29;
  public static final int BEGIN = 3;
  public static final int PLUS = 26;
  public static final int ASSIGN = 30;
  public static final int IF = 21;
  public static final int ID = 50;
  public static final int LE = 35;
  public static final int EOF = 0;
  public static final int RETURN = 20;
  public static final int INT_CONST = 46;
  public static final int TRUE = 18;
  public static final int error = 1;
  public static final int PROGRAM = 2;
  public static final int PIPE = 45;
  public static final int EQ = 36;
  public static final int TIMES = 28;
  public static final int COLON = 6;
  public static final int ELSE = 23;
  public static final int WHILE = 24;
  public static final int THEN = 22;
  public static final int NE = 37;
  public static final int END = 4;
  public static final int LPAR = 9;
  public static final int STRING = 16;
  public static final int DEF = 8;
  public static final int LBRAC = 11;
  public static final int FALSE = 19;
  public static final int STRING_CONST = 48;
  public static final int GT = 32;
  public static final int DO = 25;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PROGRAM",
  "BEGIN",
  "END",
  "SEMI",
  "COLON",
  "COMMA",
  "DEF",
  "LPAR",
  "RPAR",
  "LBRAC",
  "RBRAC",
  "INT",
  "BOOL",
  "DOUBLE",
  "STRING",
  "CHAR",
  "TRUE",
  "FALSE",
  "RETURN",
  "IF",
  "THEN",
  "ELSE",
  "WHILE",
  "DO",
  "PLUS",
  "MINUS",
  "TIMES",
  "DIV",
  "ASSIGN",
  "ASSIGNDECL",
  "GT",
  "GE",
  "LT",
  "LE",
  "EQ",
  "NE",
  "NOT",
  "AND",
  "OR",
  "IN",
  "OUT",
  "OUTNL",
  "REF",
  "PIPE",
  "INT_CONST",
  "DOUBLE_CONST",
  "STRING_CONST",
  "CHAR_CONST",
  "ID"
  };
}

